server:
  port: 8000

spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/EP_IAM
    password: 123456
    driver-class-name: org.postgresql.Driver
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: yyyy-MM-dd'T'HH:mm:ss
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        '[format_sql]': true
        '[use_sql_comments]': true